=== BillTheBest/xerela/trunk/org.xerela.net/resources/credentialKeys.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:annotation>
    <xs:documentation>The credentialDefinitions are used to generate credentialKeys in code. These
      keys are how a UI knows what credentials to ask for and how to display each
    credential.</xs:documentation>
  </xs:annotation>
  <xs:element name="credentialDefinitions">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="credentialKey"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="credentialKey">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation>The name of the credential. This is the key for the new Credential
          type.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="displayName" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation>This is what a UI should display for this credential
          name.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="displayAsPassword" use="required" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>When set to true, a UI should mask out the credential value, as if it
            were a password.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="static" use="required" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>When set to true, a UI should assume any tasks that overwrite
            credentials from the user don't need to overwrite this credential. This is useful for
            credentials like a 'jumphostip'. The user may have their own username and password but
            they wouldn't overwrite a jumphostip.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BillTheBest/xerela/org.xerela.net/resources/credentialKeys.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Defines the credential keys that will dictate how a UI displays the credentials -->
<credentialDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="credentialKeys.xsd">
    <credentialKey name="username" displayName="Username" displayAsPassword="false" static="false"/>
    <credentialKey name="password" displayName="Password" displayAsPassword="true" static="false"/>
    <credentialKey name="enableUsername" displayName="Enable Username" displayAsPassword="false" static="false"/>
    <credentialKey name="enablePassword" displayName="Enable Password" displayAsPassword="true" static="false"/>
    <credentialKey name="roCommunityString" displayName="SNMP Get Community" displayAsPassword="true" static="false"/>
    <credentialKey name="rwCommunityString" displayName="SNMP Set Community" displayAsPassword="true" static="false"/>
    <credentialKey name="snmpUsername" displayName="SNMPv3 Authentication Username" displayAsPassword="false" static="false"/>
    <credentialKey name="snmpAuthPassword" displayName="SNMPv3 Authentication Password" displayAsPassword="true" static="false"/>
    <credentialKey name="snmpPrivPassword" displayName="SNMPv3 Privacy Password" displayAsPassword="true" static="false"/>
</credentialDefinitions>
